--
-- PostgreSQL database dump
--

\restrict zjigfzE1m4fdCW1oZ2yn7qtSeGS1mVE9vbxTwkM72eVsBsr85tkbNKe9WYO7kkQ

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2026-01-19 18:47:07

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 227 (class 1259 OID 18462)
-- Name: MaintenanceRecords; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MaintenanceRecords" (
    "Id" integer NOT NULL,
    "VendingMachineId" integer NOT NULL,
    "MaintenanceDate" timestamp with time zone NOT NULL,
    "Description" text NOT NULL,
    "Problems" text NOT NULL,
    "MaintainerId" integer NOT NULL
);


ALTER TABLE public."MaintenanceRecords" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 18461)
-- Name: MaintenanceRecords_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."MaintenanceRecords" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."MaintenanceRecords_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 18396)
-- Name: Products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Products" (
    "Id" integer NOT NULL,
    "InventoryNumber" text NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "Price" numeric NOT NULL,
    "StockQuantity" integer NOT NULL,
    "MinimumStockLevel" integer NOT NULL,
    "SalesTendency" text NOT NULL
);


ALTER TABLE public."Products" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 18395)
-- Name: Products_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Products" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Products_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 18486)
-- Name: Sales; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Sales" (
    "Id" integer NOT NULL,
    "VendingMachineId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "SaleAmount" numeric NOT NULL,
    "SaleDateTime" timestamp with time zone NOT NULL,
    "PaymentMethodSale" integer NOT NULL
);


ALTER TABLE public."Sales" OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 18485)
-- Name: Sales_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Sales" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Sales_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 18412)
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "FIO" text NOT NULL,
    "Email" text NOT NULL,
    "Phone" text,
    "Role" integer NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 18411)
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 18424)
-- Name: VendingMachines; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."VendingMachines" (
    "Id" integer NOT NULL,
    "Location" text NOT NULL,
    "Model" text NOT NULL,
    "Type" text NOT NULL,
    "TotalRevenue" numeric NOT NULL,
    "SerialNumber" text,
    "InventoryNumber" text,
    "Manufacturer" text NOT NULL,
    "ManufactureDate" timestamp with time zone NOT NULL,
    "CommissioningDate" timestamp with time zone NOT NULL,
    "LastCalibrationDate" timestamp with time zone NOT NULL,
    "CalibrationIntervalMonths" integer NOT NULL,
    "ResourceHours" integer NOT NULL,
    "NextMaintenanceDate" timestamp with time zone NOT NULL,
    "MaintenanceDurationHours" integer NOT NULL,
    "Status" text NOT NULL,
    "ProductionCountry" text NOT NULL,
    "InventoryDate" timestamp with time zone NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT check_calibration_interval_positive CHECK (("CalibrationIntervalMonths" > 0)),
    CONSTRAINT check_commissioning_date CHECK ((("CommissioningDate" >= "ManufactureDate") AND ("CommissioningDate" <= CURRENT_DATE))),
    CONSTRAINT check_inventory_date CHECK ((("InventoryDate" >= "ManufactureDate") AND ("InventoryDate" <= CURRENT_DATE))),
    CONSTRAINT check_last_calibration_date CHECK ((("LastCalibrationDate" >= "ManufactureDate") AND ("LastCalibrationDate" <= CURRENT_DATE))),
    CONSTRAINT check_maintenance_duration_range CHECK ((("MaintenanceDurationHours" >= 1) AND ("MaintenanceDurationHours" <= 20))),
    CONSTRAINT check_next_maintenance_date CHECK (("NextMaintenanceDate" > CURRENT_DATE)),
    CONSTRAINT check_resource_hours_positive CHECK (("ResourceHours" > 0)),
    CONSTRAINT check_total_revenue_positive CHECK (("TotalRevenue" >= (0)::numeric))
);


ALTER TABLE public."VendingMachines" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 18423)
-- Name: VendingMachines_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."VendingMachines" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."VendingMachines_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 18388)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 5067 (class 0 OID 18462)
-- Dependencies: 227
-- Data for Name: MaintenanceRecords; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5061 (class 0 OID 18396)
-- Dependencies: 221
-- Data for Name: Products; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5069 (class 0 OID 18486)
-- Dependencies: 229
-- Data for Name: Sales; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5063 (class 0 OID 18412)
-- Dependencies: 223
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5065 (class 0 OID 18424)
-- Dependencies: 225
-- Data for Name: VendingMachines; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5059 (class 0 OID 18388)
-- Dependencies: 219
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."__EFMigrationsHistory" VALUES ('20260119154034_Init', '10.0.2');


--
-- TOC entry 5075 (class 0 OID 0)
-- Dependencies: 226
-- Name: MaintenanceRecords_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."MaintenanceRecords_Id_seq"', 1, false);


--
-- TOC entry 5076 (class 0 OID 0)
-- Dependencies: 220
-- Name: Products_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Products_Id_seq"', 1, false);


--
-- TOC entry 5077 (class 0 OID 0)
-- Dependencies: 228
-- Name: Sales_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Sales_Id_seq"', 1, false);


--
-- TOC entry 5078 (class 0 OID 0)
-- Dependencies: 222
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 1, false);


--
-- TOC entry 5079 (class 0 OID 0)
-- Dependencies: 224
-- Name: VendingMachines_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."VendingMachines_Id_seq"', 1, false);


--
-- TOC entry 4902 (class 2606 OID 18474)
-- Name: MaintenanceRecords PK_MaintenanceRecords; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MaintenanceRecords"
    ADD CONSTRAINT "PK_MaintenanceRecords" PRIMARY KEY ("Id");


--
-- TOC entry 4891 (class 2606 OID 18410)
-- Name: Products PK_Products; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "PK_Products" PRIMARY KEY ("Id");


--
-- TOC entry 4906 (class 2606 OID 18499)
-- Name: Sales PK_Sales; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sales"
    ADD CONSTRAINT "PK_Sales" PRIMARY KEY ("Id");


--
-- TOC entry 4893 (class 2606 OID 18422)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- TOC entry 4896 (class 2606 OID 18455)
-- Name: VendingMachines PK_VendingMachines; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."VendingMachines"
    ADD CONSTRAINT "PK_VendingMachines" PRIMARY KEY ("Id");


--
-- TOC entry 4889 (class 2606 OID 18394)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4899 (class 1259 OID 18510)
-- Name: IX_MaintenanceRecords_MaintainerId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MaintenanceRecords_MaintainerId" ON public."MaintenanceRecords" USING btree ("MaintainerId");


--
-- TOC entry 4900 (class 1259 OID 18511)
-- Name: IX_MaintenanceRecords_VendingMachineId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MaintenanceRecords_VendingMachineId" ON public."MaintenanceRecords" USING btree ("VendingMachineId");


--
-- TOC entry 4903 (class 1259 OID 18512)
-- Name: IX_Sales_ProductId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Sales_ProductId" ON public."Sales" USING btree ("ProductId");


--
-- TOC entry 4904 (class 1259 OID 18513)
-- Name: IX_Sales_VendingMachineId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Sales_VendingMachineId" ON public."Sales" USING btree ("VendingMachineId");


--
-- TOC entry 4894 (class 1259 OID 18514)
-- Name: IX_VendingMachines_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_VendingMachines_UserId" ON public."VendingMachines" USING btree ("UserId");


--
-- TOC entry 4897 (class 1259 OID 18515)
-- Name: uniq_vendingmachine_inventory_number; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uniq_vendingmachine_inventory_number ON public."VendingMachines" USING btree ("InventoryNumber");


--
-- TOC entry 4898 (class 1259 OID 18516)
-- Name: uniq_vendingmachine_serial_number; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uniq_vendingmachine_serial_number ON public."VendingMachines" USING btree ("SerialNumber");


--
-- TOC entry 4908 (class 2606 OID 18475)
-- Name: MaintenanceRecords FK_MaintenanceRecords_Users_MaintainerId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MaintenanceRecords"
    ADD CONSTRAINT "FK_MaintenanceRecords_Users_MaintainerId" FOREIGN KEY ("MaintainerId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 4909 (class 2606 OID 18480)
-- Name: MaintenanceRecords FK_MaintenanceRecords_VendingMachines_VendingMachineId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MaintenanceRecords"
    ADD CONSTRAINT "FK_MaintenanceRecords_VendingMachines_VendingMachineId" FOREIGN KEY ("VendingMachineId") REFERENCES public."VendingMachines"("Id") ON DELETE CASCADE;


--
-- TOC entry 4910 (class 2606 OID 18500)
-- Name: Sales FK_Sales_Products_ProductId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sales"
    ADD CONSTRAINT "FK_Sales_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."Products"("Id") ON DELETE CASCADE;


--
-- TOC entry 4911 (class 2606 OID 18505)
-- Name: Sales FK_Sales_VendingMachines_VendingMachineId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sales"
    ADD CONSTRAINT "FK_Sales_VendingMachines_VendingMachineId" FOREIGN KEY ("VendingMachineId") REFERENCES public."VendingMachines"("Id") ON DELETE CASCADE;


--
-- TOC entry 4907 (class 2606 OID 18456)
-- Name: VendingMachines FK_VendingMachines_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."VendingMachines"
    ADD CONSTRAINT "FK_VendingMachines_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


-- Completed on 2026-01-19 18:47:07

--
-- PostgreSQL database dump complete
--

\unrestrict zjigfzE1m4fdCW1oZ2yn7qtSeGS1mVE9vbxTwkM72eVsBsr85tkbNKe9WYO7kkQ

